# Generated by Django 3.1.2 on 2021-01-03 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_comment_subcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, related_name='commented', to=settings.AUTH_USER_MODEL),
        ),
    ]
