# Generated by Django 3.1.2 on 2021-01-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=100)),
                ('Book_Title', models.CharField(max_length=200)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Year_Of_Publication', models.IntegerField()),
                ('Publisher', models.CharField(max_length=200)),
                ('Image_URL_S', models.CharField(max_length=200)),
                ('Image_URL_M', models.CharField(max_length=200)),
                ('Image_URL_L', models.CharField(max_length=200)),
            ],
        ),
    ]
