# Generated by Django 3.1.2 on 2021-01-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210107_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='Book_Author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='Book_Title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='ISBN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='Image_URL_L',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='Image_URL_M',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='Image_URL_S',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='Publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='Year_Of_Publication',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
