# Generated by Django 3.1.2 on 2021-01-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210111_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='ISBN',
            field=models.BigIntegerField(null=True),
        ),
    ]
